### ISSUE TITLE
質問: オープンカタログ一覧.csvの行数と、example.csvの行数が異なる

### ISSUE THREAD

**Issue by Uemmra3** [mh61503891/tottori-opendata-catalog#2]
当方Ruby環境がないので、参考まで

v0.5の結果で行数 (見出しを除くもの) を比較しました。
オープンカタログ一覧.csv　128行
example.csv 131行
となっている。

そもそもシステムを理解していないのでアレですが、この行数は一致するべきなのでは？

**Comment by mh61503891** [comment]
コメントありがとうございます！

おそらくオープンカタログ一覧.csvの方は職員さんがシステムからエクスポートしたCSVだと思います。

差分を確認してみました。

```bash
$ tottori-opendata-catalog csv > a.csv
$ wget 'http://db.pref.tottori.jp/opendataResearch.nsf/e92cd7f95a94c9c249257c92000236b8/08e699ed3190c88b49257db0000be942/$FILE/%E3%82%AA%E3%83%BC%E3%83%97%E3%83%B3%E3%82%AB%E3%82%BF%E3%83%AD%E3%82%B0%E4%B8%80%E8%A6%A7.csv' -O b.csv
```

```bash
$ nkf -w -Lu a.csv | sed 1d | wc
     131     535   32060
$ nkf -w -Lu b.csv | sed 1d | wc
     128     259   14979
```

確かに3件多いですね…。

書式を統一して比較してみます。

```diff
colordiff <(nkf -w -Lu a.csv | sed 1d | awk 'BEGIN{FS=","}{print $4,$5,$2}' | sort) <(nkf -w -Lu b.csv | sed 1d | awk 'BEGIN{FS=","}{print $2,$3,$4}' | sort)
```

diffの結果です。

```diff
49d48
< 地域振興部 統計課 鳥取県鉱工業指数
57a57
> 地域振興部 統計課 鳥取県鉱工業生産動態調査
71d70
< 会計管理者 会計指導課 鳥取県収入証紙の販売所
80d78
< 地域振興部 地域振興課 普通会計当初予算（市町村分）
81a80
> 地域振興部 地域振興課 普通会計当初予算（市町村分） 
87d85
< 福祉保健部 子育て応援課 鳥取県少子化対策等に関するアンケート
108,109c106,107
< 元気づくり総本部 県民課 監査調書
< 元気づくり総本部 県民課 審議会情報
---
> 未来づくり推進局 県民課 監査調書
> 未来づくり推進局 県民課 審議会情報
111d108
< 元気づくり総本部 広報課 とっとり県政だより
113c110
< 元気づくり総本部 県民課 一定の公職者からの提言等
---
> 未来づくり推進局 県民課 一定の公職者からの提言等
```

少し見づらいですが、増えたのは以下の3件です。こっちの方はスクレイピングしたものですので最新のデータです。

1. 会計管理者 会計指導課 鳥取県収入証紙の販売所
2. 元気づくり総本部 広報課 とっとり県政だより
3. 福祉保健部 子育て応援課 鳥取県少子化対策等に関するアンケート

あとは部局名の変更と、データの変更のようです。

- 鳥取県鉱工業指数 → 鳥取県鉱工業生産動態調査
- 部局名前変更: 元気づくり総本部 → 未来づくり推進局

**Comment by Uemmra3** [comment]
仕事早っww
なんとなくわかりました。
> "おそらくオープンカタログ一覧.csvの方は職員さんがシステムからエクスポートしたCSVだと思います。"
ということで、時差があるのですね。

カタログに関しては、更新頻度を上げてほしい(というか、自動化しておくべき)ですが、
システムの予算面とか、何らかの制約でそうなってないのかもしれません。
